// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void StartUp_Animation( lv_obj_t *TargetObject, int delay);
void StartUp2_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_StartUpPage
void ui_StartUpPage_screen_init(void);
void ui_event_StartUpPage( lv_event_t * e);
lv_obj_t *ui_StartUpPage;
lv_obj_t *ui_ImgCoreText;
lv_obj_t *ui_ImgS3Logo;
// CUSTOM VARIABLES
lv_obj_t *ui_StartUpPage;
lv_obj_t *ui_ImgCoreText;
lv_obj_t *ui_ImgS3Logo;


// SCREEN: ui_WifiConfigPage
void ui_WifiConfigPage_screen_init(void);
void ui_event_WifiConfigPage( lv_event_t * e);
lv_obj_t *ui_WifiConfigPage;
lv_obj_t *ui_ImgWifiLogo;
void ui_event_PanelWifiStatus( lv_event_t * e);
lv_obj_t *ui_PanelWifiStatus;
lv_obj_t *ui_LabelSSID;
lv_obj_t *ui_LabelRSSI;
lv_obj_t *ui_LabelIP;
void ui_event_ResetWifi( lv_event_t * e);
lv_obj_t *ui_ResetWifi;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_LabelWifiStatus;
lv_obj_t *ui_SpinnerWifiConnecting;
// CUSTOM VARIABLES
lv_obj_t *ui_WifiConfigPage;
lv_obj_t *ui_ImgWifiLogo;
lv_obj_t *ui_PanelWifiStatus;
lv_obj_t *ui_LabelSSID;
lv_obj_t *ui_LabelRSSI;
lv_obj_t *ui_LabelIP;
lv_obj_t *ui_ResetWifi;
lv_obj_t *ui_LabelWifiStatus;
lv_obj_t *ui_SpinnerWifiConnecting;


// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main( lv_event_t * e);
lv_obj_t *ui_Main;
// CUSTOM VARIABLES
lv_obj_t *ui_Main;

// EVENTS
void ui_event____initial_actions0( lv_event_t * e);
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void StartUp_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, -100, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);

}
void StartUp2_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 100, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_StartUpPage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_WifiConfigPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_WifiConfigPage_screen_init);
}
}

void ui_event_WifiConfigPage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onWifiConfigPageLoaded( e );
}
if ( event_code == LV_EVENT_SCREEN_UNLOADED) {
      onWifiConfigPageUnloaded( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Main_screen_init);
}
}

void ui_event_PanelWifiStatus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      onResetWifi( e );
}
}

void ui_event_ResetWifi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      onResetWifi( e );
}
}

void ui_event_Main( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_WifiConfigPage, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_WifiConfigPage_screen_init);
}
}

void ui_event____initial_actions0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      StartUp_Animation(ui_ImgCoreText, 0);
      StartUp2_Animation(ui_ImgS3Logo, 0);
      PlayStartupMusic( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_StartUpPage_screen_init();
ui_WifiConfigPage_screen_init();
ui_Main_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

lv_disp_load_scr(ui____initial_actions0);
lv_disp_load_scr( ui_StartUpPage);
}
