// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void StartUp_Animation( lv_obj_t *TargetObject, int delay);
void StartUp2_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_StartUpPage
void ui_StartUpPage_screen_init(void);
void ui_event_StartUpPage( lv_event_t * e);
extern lv_obj_t *ui_StartUpPage;
extern lv_obj_t *ui_ImgCoreText;
extern lv_obj_t *ui_ImgS3Logo;
// CUSTOM VARIABLES
extern lv_obj_t *ui_StartUpPage;
extern lv_obj_t *ui_ImgCoreText;
extern lv_obj_t *ui_ImgS3Logo;

// SCREEN: ui_WifiConfigPage
void ui_WifiConfigPage_screen_init(void);
void ui_event_WifiConfigPage( lv_event_t * e);
extern lv_obj_t *ui_WifiConfigPage;
extern lv_obj_t *ui_ImgWifiLogo;
void ui_event_PanelWifiStatus( lv_event_t * e);
extern lv_obj_t *ui_PanelWifiStatus;
extern lv_obj_t *ui_LabelSSID;
extern lv_obj_t *ui_LabelRSSI;
extern lv_obj_t *ui_LabelIP;
void ui_event_ResetWifi( lv_event_t * e);
extern lv_obj_t *ui_ResetWifi;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_LabelWifiStatus;
extern lv_obj_t *ui_SpinnerWifiConnecting;
// CUSTOM VARIABLES
extern lv_obj_t *ui_WifiConfigPage;
extern lv_obj_t *ui_ImgWifiLogo;
extern lv_obj_t *ui_PanelWifiStatus;
extern lv_obj_t *ui_LabelSSID;
extern lv_obj_t *ui_LabelRSSI;
extern lv_obj_t *ui_LabelIP;
extern lv_obj_t *ui_ResetWifi;
extern lv_obj_t *ui_LabelWifiStatus;
extern lv_obj_t *ui_SpinnerWifiConnecting;

// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main( lv_event_t * e);
extern lv_obj_t *ui_Main;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Main;

// EVENTS
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_core_text_png);   // assets/core_text.png
LV_IMG_DECLARE( ui_img_s3_text_png);   // assets/s3_text.png
LV_IMG_DECLARE( ui_img_1024934270);   // assets/wifi-logo.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
