// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_StartUpPage_screen_init(void)
{
ui_StartUpPage = lv_obj_create(NULL);
lv_obj_remove_flag( ui_StartUpPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_StartUpPage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BGCOLOR);
ui_object_set_themeable_style_property(ui_StartUpPage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BGCOLOR);

ui_ImgCoreText = lv_image_create(ui_StartUpPage);
lv_image_set_src(ui_ImgCoreText, &ui_img_core_text_png);
lv_obj_set_width( ui_ImgCoreText, LV_SIZE_CONTENT);  /// 162
lv_obj_set_height( ui_ImgCoreText, LV_SIZE_CONTENT);   /// 46
lv_obj_set_x( ui_ImgCoreText, 0 );
lv_obj_set_y( ui_ImgCoreText, -50 );
lv_obj_set_align( ui_ImgCoreText, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgCoreText, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_ImgCoreText, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImgS3Logo = lv_image_create(ui_StartUpPage);
lv_image_set_src(ui_ImgS3Logo, &ui_img_s3_text_png);
lv_obj_set_width( ui_ImgS3Logo, LV_SIZE_CONTENT);  /// 163
lv_obj_set_height( ui_ImgS3Logo, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_ImgS3Logo, 0 );
lv_obj_set_y( ui_ImgS3Logo, 30 );
lv_obj_set_align( ui_ImgS3Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgS3Logo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_ImgS3Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_StartUpPage, ui_event_StartUpPage, LV_EVENT_ALL, NULL);
ui_StartUpPage = ui_StartUpPage;
ui_ImgCoreText = ui_ImgCoreText;
ui_ImgS3Logo = ui_ImgS3Logo;

}
