// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_WifiConfigPage_screen_init(void)
{
ui_WifiConfigPage = lv_obj_create(NULL);
lv_obj_remove_flag( ui_WifiConfigPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImgWifiLogo = lv_image_create(ui_WifiConfigPage);
lv_image_set_src(ui_ImgWifiLogo, &ui_img_1024934270);
lv_obj_set_width( ui_ImgWifiLogo, 100);
lv_obj_set_height( ui_ImgWifiLogo, 100);
lv_obj_set_x( ui_ImgWifiLogo, -96 );
lv_obj_set_y( ui_ImgWifiLogo, -20 );
lv_obj_set_align( ui_ImgWifiLogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgWifiLogo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_ImgWifiLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_ImgWifiLogo,80);

ui_PanelWifiStatus = lv_obj_create(ui_WifiConfigPage);
lv_obj_set_width( ui_PanelWifiStatus, 192);
lv_obj_set_height( ui_PanelWifiStatus, 140);
lv_obj_set_x( ui_PanelWifiStatus, 57 );
lv_obj_set_y( ui_PanelWifiStatus, -16 );
lv_obj_set_align( ui_PanelWifiStatus, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelWifiStatus,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelWifiStatus, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_PanelWifiStatus, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_remove_flag( ui_PanelWifiStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelSSID = lv_label_create(ui_PanelWifiStatus);
lv_obj_set_width( ui_LabelSSID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSSID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSSID, 29 );
lv_obj_set_y( ui_LabelSSID, -53 );
lv_obj_set_align( ui_LabelSSID, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSSID,"SSID: ");
lv_obj_set_style_text_font(ui_LabelSSID, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelRSSI = lv_label_create(ui_PanelWifiStatus);
lv_obj_set_width( ui_LabelRSSI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRSSI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelRSSI, 0 );
lv_obj_set_y( ui_LabelRSSI, 12 );
lv_obj_set_align( ui_LabelRSSI, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelRSSI,"RSSI: ");
lv_obj_set_style_text_font(ui_LabelRSSI, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelIP = lv_label_create(ui_PanelWifiStatus);
lv_obj_set_width( ui_LabelIP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelIP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelIP, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelIP,"IP: ");
lv_obj_set_style_text_font(ui_LabelIP, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ResetWifi = lv_button_create(ui_PanelWifiStatus);
lv_obj_set_height( ui_ResetWifi, 40);
lv_obj_set_width( ui_ResetWifi, lv_pct(100));
lv_obj_set_x( ui_ResetWifi, -6 );
lv_obj_set_y( ui_ResetWifi, -15 );
lv_obj_set_align( ui_ResetWifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ResetWifi, LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_ResetWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ResetWifi, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ResetWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_ResetWifi);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"RESET WIFI");
lv_obj_set_style_text_decor(ui_Label1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_WifiConfigPage);
lv_obj_set_width( ui_Panel2, 320);
lv_obj_set_height( ui_Panel2, 50);
lv_obj_set_align( ui_Panel2, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x989898), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWifiStatus = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_LabelWifiStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWifiStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelWifiStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWifiStatus,"Connecting ...");
lv_obj_set_style_text_color(ui_LabelWifiStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWifiStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWifiStatus, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpinnerWifiConnecting = lv_spinner_create(ui_WifiConfigPage);
//lv_spinner_set_anim_params(ui_SpinnerWifiConnecting, 1000, 90);
lv_obj_set_width( ui_SpinnerWifiConnecting, 100);
lv_obj_set_height( ui_SpinnerWifiConnecting, 100);
lv_obj_set_x( ui_SpinnerWifiConnecting, 65 );
lv_obj_set_y( ui_SpinnerWifiConnecting, -21 );
lv_obj_set_align( ui_SpinnerWifiConnecting, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_SpinnerWifiConnecting, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_width(ui_SpinnerWifiConnecting, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_SpinnerWifiConnecting, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ResetWifi, ui_event_ResetWifi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelWifiStatus, ui_event_PanelWifiStatus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WifiConfigPage, ui_event_WifiConfigPage, LV_EVENT_ALL, NULL);
ui_WifiConfigPage = ui_WifiConfigPage;
ui_ImgWifiLogo = ui_ImgWifiLogo;
ui_PanelWifiStatus = ui_PanelWifiStatus;
ui_LabelSSID = ui_LabelSSID;
ui_LabelRSSI = ui_LabelRSSI;
ui_LabelIP = ui_LabelIP;
ui_ResetWifi = ui_ResetWifi;
ui_LabelWifiStatus = ui_LabelWifiStatus;
ui_SpinnerWifiConnecting = ui_SpinnerWifiConnecting;

}
